const defaultIconKey = 'chuangye'

const iconAliases: Record<string, string> = {
  briefcase: 'chuangye',
  rocket: 'fabu',
  broken_heart: 'xinsui',
  shirt: 'meirong',
  game: 'youxi',
  'meirong-copy': 'meirong_copy',
  'a-068_jianzhi': 'a_068_jianzhi',
}

const iconClassByKey: Record<string, string> = {
  chuangye: 'icon-chuangye',
  xinsui: 'icon-xinsui',
  jianshen: 'icon-jianshen',
  paobu1: 'icon-paobu1',
  yuedu: 'icon-yuedu',
  daima: 'icon-daima',
  youxi: 'icon-youxi',
  naozhong: 'icon-naozhong',
  jinqian: 'icon-jinqian',
  kafei: 'icon-kafei',
  youyong: 'icon-youyong',
  lanqiu: 'icon-lanqiu',
  kezuofan: 'icon-kezuofan',
  naichaxiaochi: 'icon-naichaxiaochi',
  lingshi: 'icon-lingshi',
  jucan: 'icon-jucan',
  jingchanghejiu: 'icon-jingchanghejiu',
  smoking: 'icon-smoking',
  bushengbing: 'icon-bushengbing',
  yiyuan: 'icon-yiyuan',
  meirong: 'icon-meirong',
  meirong_copy: 'icon-meirong-copy',
  aiqingyuehui: 'icon-aiqingyuehui',
  shejiao: 'icon-shejiao',
  tongxun: 'icon-tongxun',
  lvyou: 'icon-lvyou',
  qiche: 'icon-qiche',
  zhufang: 'icon-zhufang',
  weixiuoff: 'icon-weixiuoff',
  xiangzi: 'icon-xiangzi',
  chuangye3: 'icon-chuangye3',
  a_068_jianzhi: 'icon-a-068_jianzhi',
  fabu: 'icon-fabu',
  shouye: 'icon-shouye',
  dantupailie: 'icon-dantupailie',
  luyin: 'icon-luyin',
  sanjiaoxing: 'icon-sanjiaoxing',
  xiazai49: 'icon-xiazai49',
  yule: 'icon-yule',
  qita: 'icon-qita',
  qita1: 'icon-qita1',
  qita2: 'icon-qita2',
  qitafuwu: 'icon-qitafuwu',
}

export const lumaIconOptions = [
  { key: 'chuangye', theme: 'green' },
  { key: 'xinsui', theme: 'red' },
  { key: 'jianshen', theme: 'orange' },
  { key: 'paobu1', theme: 'green' },
  { key: 'yuedu', theme: 'teal' },
  { key: 'daima', theme: 'purple' },
  { key: 'youxi', theme: 'purple' },
  { key: 'naozhong', theme: 'orange' },
  { key: 'jinqian', theme: 'green' },
  { key: 'kafei', theme: 'orange' },
  { key: 'youyong', theme: 'teal' },
  { key: 'lanqiu', theme: 'orange' },
  { key: 'kezuofan', theme: 'orange' },
  { key: 'naichaxiaochi', theme: 'orange' },
  { key: 'lingshi', theme: 'orange' },
  { key: 'jucan', theme: 'orange' },
  { key: 'jingchanghejiu', theme: 'red' },
  { key: 'smoking', theme: 'red' },
  { key: 'bushengbing', theme: 'green' },
  { key: 'yiyuan', theme: 'green' },
  { key: 'meirong', theme: 'pink' },
  { key: 'meirong_copy', theme: 'pink' },
  { key: 'aiqingyuehui', theme: 'pink' },
  { key: 'shejiao', theme: 'blue' },
  { key: 'tongxun', theme: 'blue' },
  { key: 'lvyou', theme: 'teal' },
  { key: 'qiche', theme: 'blue' },
  { key: 'zhufang', theme: 'blue' },
  { key: 'weixiuoff', theme: 'gray' },
  { key: 'xiangzi', theme: 'gray' },
  { key: 'chuangye3', theme: 'green' },
  { key: 'a_068_jianzhi', theme: 'blue' },
  { key: 'fabu', theme: 'green' },
  { key: 'shouye', theme: 'green' },
  { key: 'dantupailie', theme: 'gray' },
  { key: 'luyin', theme: 'green' },
  { key: 'sanjiaoxing', theme: 'orange' },
  { key: 'xiazai49', theme: 'blue' },
  { key: 'yule', theme: 'purple' },
  { key: 'qita', theme: 'gray' },
  { key: 'qita1', theme: 'gray' },
  { key: 'qita2', theme: 'gray' },
  { key: 'qitafuwu', theme: 'gray' },
] as const

export function normalizeLumaIconKey(key?: string | null) {
  const normalized = key ? iconAliases[key] ?? key : defaultIconKey
  return iconClassByKey[normalized] ? normalized : defaultIconKey
}

export function lumaIconClass(key?: string | null) {
  return iconClassByKey[normalizeLumaIconKey(key)] ?? iconClassByKey[defaultIconKey]
}
